### ISSUE TITLE
build error: module is not installed

### ISSUE THREAD

**Issue by 4781121** [evonove/mut#6]
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:///main.qml:7 module "Mut.Themes" is not installed
qrc:///main.qml:6 module "Mut.Styles" is not installed
qrc:///main.qml:5 module "Mut" is not installed
qrc:///main.qml:9 module "Mut.ListItems" is not installed
qrc:///main.qml:8 module "Mut.Layouts" is not installed
qrc:///main.qml:7 module "Mut.Themes" is not installed
qrc:///main.qml:6 module "Mut.Styles" is not installed
qrc:///main.qml:5 module "Mut" is not installed
qrc:///main.qml:9 module "Mut.ListItems" is not installed
qrc:///main.qml:8 module "Mut.Layouts" is not installed
qrc:///main.qml:7 module "Mut.Themes" is not installed
qrc:///main.qml:6 module "Mut.Styles" is not installed
qrc:///main.qml:5 module "Mut" is not installed
qrc:///main.qml:9 module "Mut.ListItems" is not installed
qrc:///main.qml:8 module "Mut.Layouts" is not installed
qrc:///main.qml:7 module "Mut.Themes" is not installed
qrc:///main.qml:6 module "Mut.Styles" is not installed
qrc:///main.qml:5 module "Mut" is not installed
qrc:///main.qml:9 module "Mut.ListItems" is not installed
qrc:///main.qml:8 module "Mut.Layouts" is not installed
qrc:///main.qml:7 module "Mut.Themes" is not installed
qrc:///main.qml:6 module "Mut.Styles" is not installed
qrc:///main.qml:5 module "Mut" is not installed
qrc:///main.qml:9 module "Mut.ListItems" is not installed
qrc:///main.qml:8 module "Mut.Layouts" is not installed

**Comment by dubik** [comment]
just for the record...

```
diff --git a/examples/app/main.cpp b/examples/app/main.cpp
index 00f5830..be1f90c 100644
--- a/examples/app/main.cpp
+++ b/examples/app/main.cpp
@@ -5,7 +5,7 @@ int main(int argc, char *argv[])
 {
   QApplication app(argc, argv);
   QQmlApplicationEngine engine;
-  engine.addImportPath(QApplication::applicationDirPath() + QStringLiteral("/../../modules"));
+  engine.addImportPath(QApplication::applicationDirPath() + QStringLiteral("/../../../../../modules"));
   engine.load(QUrl(QStringLiteral("qrc:///main.qml")));
 
   return app.exec();
